server:
  error:
    include-message: never
    include-binding-errors: never

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://167.235.62.238:31111/EnergyOprator
    username: bot
    password: uwYyYKbsjjep

  jpa:
    hibernate:
      ddl-auto: create-drop # When you launch the application for the first time - switch "none" at "create"
      show-sql: false
      database: postgres
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      open-in-view: false
      generate-ddl: true
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: error
    org.hibernate: error
